# Generated by Django 4.1.4 on 2022-12-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familair1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('nacimiento', models.IntegerField()),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Familair2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('nacimiento', models.IntegerField()),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Familiar3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('nacimiento', models.IntegerField()),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
