# Generated by Django 4.1.4 on 2022-12-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familair2',
            new_name='Familia',
        ),
        migrations.DeleteModel(
            name='Familair1',
        ),
        migrations.DeleteModel(
            name='Familiar3',
        ),
    ]
